export * from "./app.interface";
export * from "./favorites.interfaces";
export * from "./history.interfaces";
export * from "./home.interfaces";
export * from "./movies.interfaces";
export * from "./series.interface";
export * from "./people.interface";
export * from "./user.interfaces";
export * from "./people.interface";
